In [1]:
from functions import AddNoActivity, scaling
from average_metrics import average_bal_acc_score, average_f1_score, average_acc_score, average_hamming_loss
from classifiers import SupportVectorMachine, LogisticRegression, RandomForest, KNearestNeighbour, AdaBoost, XGBoost
from sklearn.model_selection import train_test_split
import pandas as pd

In [2]:
whole_data = []
for subject in range(1,9):
    for i in range(1,7):
        ts = pd.read_csv(f"D:/Reflections/Signal_Processing/train/train/subj{subject}_series{i}_data.csv")
        te = pd.read_csv(f"D:/Reflections/Signal_Processing/train/train/subj{subject}_series{i}_events.csv")
        temp = pd.concat([ts,te], axis = 1)        
        whole_data_temp = AddNoActivity(temp)
        whole_data.append(whole_data_temp)

In [3]:
data = pd.concat(whole_data)

In [4]:
data

,id,Fp1,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,O2,PO10,id,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased,NoActivity
0,subj1_series1_0,-31,363,211,121,211,15,717,279,35,...,120,704,subj1_series1_0,0,0,0,0,0,0,1
1,subj1_series1_1,-29,342,216,123,222,200,595,329,43,...,83,737,subj1_series1_1,0,0,0,0,0,0,1
2,subj1_series1_2,-172,278,105,93,222,511,471,280,12,...,62,677,subj1_series1_2,0,0,0,0,0,0,1
3,subj1_series1_3,-272,263,-52,99,208,511,428,261,27,...,58,592,subj1_series1_3,0,0,0,0,0,0,1
4,subj1_series1_4,-265,213,-67,99,155,380,476,353,32,...,67,581,subj1_series1_4,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191764,subj8_series6_191764,68,-33,445,168,118,309,338,392,314,...,426,494,subj8_series6_191764,0,0,0,0,0,0,1
191765,subj8_series6_191765,38,-78,427,142,113,288,301,366,315,...,502,578,subj8_series6_191765,0,0,0,0,0,0,1
191766,subj8_series6_191766,29,-80,422,134,99,286,313,352,323,...,528,630,subj8_series6_191766,0,0,0,0,0,0,1
191767,subj8_series6_191767,47,-68,423,127,84,279,332,348,325,...,448,607,subj8_series6_191767,0,0,0,0,0,0,1
191768,subj8_series6_191768,36,-81,425,125,93,281,292,338,306,...,449,541,subj8_series6_191768,0,0,0,0,0,0,1

In [5]:
s1 = data[data['NoActivity'] == 1]

In [6]:
s0 = data[data['NoActivity'] == 0]

In [7]:
s1 = s1.sample(n = (len(s0) + 00))

In [8]:
s1

,id,Fp1,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,O2,PO10,id,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased,NoActivity
3486,subj7_series4_3486,-172,200,91,-24,-81,188,498,206,-115,...,-148,-105,subj7_series4_3486,0,0,0,0,0,0,1
206745,subj5_series3_206745,239,206,600,-23,91,406,394,501,149,...,33,120,subj5_series3_206745,0,0,0,0,0,0,1
57233,subj4_series6_57233,-29,577,335,-34,-54,147,-282,68,139,...,-59,-33,subj4_series6_57233,0,0,0,0,0,0,1
44396,subj8_series1_44396,42,109,292,-172,-165,-23,-59,482,-41,...,-419,-436,subj8_series1_44396,0,0,0,0,0,0,1
245759,subj4_series1_245759,-285,210,637,256,134,274,119,664,-240,...,113,-5,subj4_series1_245759,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96946,subj3_series3_96946,247,121,180,150,172,615,-53,409,88,...,-146,-9,subj3_series3_96946,0,0,0,0,0,0,1
87843,subj6_series2_87843,60,234,456,183,151,233,126,323,435,...,68,-69,subj6_series2_87843,0,0,0,0,0,0,1
243709,subj2_series2_243709,439,273,81,179,-40,418,-157,58,-244,...,-444,-328,subj2_series2_243709,0,0,0,0,0,0,1
299001,subj7_series1_299001,333,925,-424,-63,-196,427,282,-179,-71,...,-253,-88,subj7_series1_299001,0,0,0,0,0,0,1
123341,subj2_series5_123341,728,384,519,197,-52,700,472,330,49,...,124,273,subj2_series5_123341,0,0,0,0,0,0,1

In [9]:
s = s1.append(s0)

In [10]:
s

,id,Fp1,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,...,O2,PO10,id,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased,NoActivity
3486,subj7_series4_3486,-172,200,91,-24,-81,188,498,206,-115,...,-148,-105,subj7_series4_3486,0,0,0,0,0,0,1
206745,subj5_series3_206745,239,206,600,-23,91,406,394,501,149,...,33,120,subj5_series3_206745,0,0,0,0,0,0,1
57233,subj4_series6_57233,-29,577,335,-34,-54,147,-282,68,139,...,-59,-33,subj4_series6_57233,0,0,0,0,0,0,1
44396,subj8_series1_44396,42,109,292,-172,-165,-23,-59,482,-41,...,-419,-436,subj8_series1_44396,0,0,0,0,0,0,1
245759,subj4_series1_245759,-285,210,637,256,134,274,119,664,-240,...,113,-5,subj4_series1_245759,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190586,subj8_series6_190586,763,1158,484,118,174,420,304,101,120,...,-292,97,subj8_series6_190586,0,0,0,0,0,1,0
190587,subj8_series6_190587,782,1143,515,124,154,403,298,132,103,...,-383,-54,subj8_series6_190587,0,0,0,0,0,1,0
190588,subj8_series6_190588,760,1088,525,146,161,384,259,150,113,...,-501,-153,subj8_series6_190588,0,0,0,0,0,1,0
190589,subj8_series6_190589,678,1038,499,123,149,367,226,144,123,...,-465,-84,subj8_series6_190589,0,0,0,0,0,1,0
190590,subj8_series6_190590,686,1036,468,113,122,358,244,118,108,...,-366,-71,subj8_series6_190590,0,0,0,0,0,1,0

In [11]:
s.reset_index(drop = True, inplace = True)

In [12]:
s.drop('id', axis = 1, inplace = True)

In [13]:
x = s.iloc[:,0:32]

In [14]:
y = s.iloc[:,32:]

In [15]:
x

,Fp1,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,FC2,...,P7,P3,Pz,P4,P8,PO9,O1,Oz,O2,PO10
0,-172,200,91,-24,-81,188,498,206,-115,-94,...,0,-229,15,10,-67,-13,-1,-229,-148,-105
1,239,206,600,-23,91,406,394,501,149,108,...,128,336,224,568,382,-15,238,19,33,120
2,-29,577,335,-34,-54,147,-282,68,139,129,...,78,-97,68,69,159,140,51,53,-59,-33
3,42,109,292,-172,-165,-23,-59,482,-41,-82,...,8,0,-72,238,-72,-423,-89,-343,-419,-436
4,-285,210,637,256,134,274,119,664,-240,171,...,622,179,333,215,375,117,254,69,113,-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257443,763,1158,484,118,174,420,304,101,120,-14,...,-348,-59,-14,-61,-8,-485,-152,-130,-292,97
2257444,782,1143,515,124,154,403,298,132,103,-29,...,-369,-87,-56,-122,-72,-498,-206,-211,-383,-54
2257445,760,1088,525,146,161,384,259,150,113,-35,...,-352,-65,-54,-147,-94,-445,-216,-280,-501,-153
2257446,678,1038,499,123,149,367,226,144,123,-18,...,-336,-59,-39,-127,-71,-387,-203,-264,-465,-84
2257447,686,1036,468,113,122,358,244,118,108,-34,...,-334,-65,-19,-113,-77,-329,-153,-180,-366,-71

In [16]:
y

,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased,NoActivity
0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,1
2,0,0,0,0,0,0,1
3,0,0,0,0,0,0,1
4,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...
2257443,0,0,0,0,0,1,0
2257444,0,0,0,0,0,1,0
2257445,0,0,0,0,0,1,0
2257446,0,0,0,0,0,1,0
2257447,0,0,0,0,0,1,0

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 42)

In [18]:
x_train = scaling(x_train)

In [19]:
x_test = scaling(x_test)

In [20]:
SupportVectorMachine(x_train, x_test, y_train, y_test)

C:\Users\91974\anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\91974\anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\91974\anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\91974\anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\91974\anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\91974\anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
C:\Users\91974\anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'

The average balanced accuracy score of the support vector classifier is 0.5032997151239468
The average accuracy score of the support vector classifier is  0.21659436637841475
The average F1 score of the support vector classifier is  0.15862157340610653
The average hamming loss of the support vector classifier is  0.7834056336215853

,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased,NoActivity
0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
1,1.0,1.0,1.0,0.0,1.0,1.0,0.0
2,1.0,1.0,1.0,1.0,1.0,1.0,0.0
3,1.0,1.0,1.0,1.0,1.0,1.0,0.0
4,1.0,1.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...
677230,1.0,1.0,1.0,1.0,1.0,1.0,0.0
677231,1.0,1.0,1.0,0.0,1.0,1.0,0.0
677232,1.0,1.0,1.0,0.0,1.0,1.0,0.0
677233,1.0,1.0,1.0,0.0,1.0,1.0,0.0
677234,1.0,1.0,1.0,0.0,1.0,1.0,0.0

In [21]:
LogisticRegression(x_train, x_test, y_train, y_test)

TypeError: LogisticRegression() got an unexpected keyword argument 'solver'

In [ ]:
RandomForest(100, x_train, x_test, y_train, y_test)

In [ ]:
KNearestNeighbour(5, x_train, x_test, y_train, y_test)

In [ ]:
AdaBoost(50, x_train, x_test, y_train, y_test)

In [ ]:
XGBoost(x_train, x_test, y_train, y_test)